name: Create JAVA Runnable JAR

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Java Build Runnable JAR
        run: ./gradlew clean build
